version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: proman-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: proman_db_user
      POSTGRES_PASSWORD: promanPassword
      POSTGRES_DB: proman
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: proman-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
